# H2 Database Konfiqurasiyas?
spring.datasource.url=jdbc:h2:mem:balance_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA Konfiqurasiyas?
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.id.new_generator_mappings=false

# Dair?vi As?l?l?q ?caz?si
spring.main.allow-circular-references=true
spring.jpa.open-in-view=false
