# H2 Database konfiqurasiyas?
spring.datasource.url=jdbc:h2:mem:balance_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.h2.console.enabled=true

# JPA parametrl?ri
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
