spring.datasource.url=jdbc:mysql://production-db-url:3306/production_balance_db
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=admin
spring.datasource.password=admin
spring.h2.console.enabled=false
server.port=8082

spring.security.user.name=prod_admin
spring.security.user.password=prod_admin_pass
spring.security.basic.enabled=true
