# application-dev.properties (Inki?af mühiti)
spring.datasource.url=jdbc:h2:mem:balance_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Server Configuration (Development)
server.port=8081

# Spring Security (Development)
spring.security.user.name=admin
spring.security.user.password=admin
spring.security.basic.enabled=false  # ?nki?af mühitind? t?hlük?sizlik deaktiv edilir
