# application-prod.properties (?stehsal mühiti)
spring.datasource.url=jdbc:mysql://production-db-url:3306/production_balance_db
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=prod_user
spring.datasource.password=prod_password
spring.h2.console.enabled=false  # H2 konsolu istehsal mühitind? deaktiv edilir

# Server Configuration (Production)
server.port=8080

# Spring Security (Production)
spring.security.user.name=prod_admin
spring.security.user.password=prod_admin_pass
spring.security.basic.enabled=true  # ?stehsalda t?hlük?sizlik aktivdir
